SELECT
    ym_s_date,
    COALESCE(ym_s_clientID, 0) AS ym_s_clientID,
    num_user,
    COALESCE(visitID, 0) AS visitID,
    model,
    content,
    cid,
    pageViews,
    dateTime_visit,
    grouping,
    source_detail,
    ym_s_startURL_domain,
    visitDuration,
    bounce,
    count_visit,
    count_goals,
    "Дилер",
    "Оптиматика_Дилер",
    "Федеральный округ",
    "Город",
    source,
    source_2,
    medium,
    campaign
FROM sttgaz.vw_total_dealers